site_name: rboc blog
site_description: My personal blog
repo_name: raulbocanegra/raulbocaengra.github.io
repo_url: https://github.com/raulbocanegra/raulbocanegra.github.io
theme:
  name: material
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  language: en

plugins:
  - search
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Rboc's Blog: index.md
